trigger:
- main
pool:
  vmImage: 'windows-latest'
steps:
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        # Write your commands here
        echo 'HEXADCT.Testautomation pipeline is triggered'
  - script: |-
     curl -X POST "http://34.206.31.192:8282/talos/external/executeTestSet" -H "accept: */*" -H "apiKey: 2cff6e67-d459-46c1-80c1-e8784ef4d4a4" -H "secretKey: 61f59437-0dad-4e4e-b95c-e3ca665db06b" -H "Content-Type: application/json" -d "{ \"loggedUserName\": \"Magesh\", \"maxNumberOfThreads\": 2, \"testSetId\": 137, \"triggeredFromApp\": \"app2\"}"